spring:
  profiles:
    active: local   #default
    group:
      local:
        - common
      prod:
        - common
#  "local", "prod" cascade "common"

---
spring:
  config:
    activate:
      on-profile: common


kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pharmacy-map
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  #      data-locations: /Users/rlo.x/Downloads/Pharmacymap/database/init/direction.sql

  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


pharmacy:
  map:
    base:
      url: http://localhost:8080/dir/


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://pharmacy-map-database:3306/pharmacy-map
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  redis:
    host: pharmacy-map-redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate # prod 배포시 validate
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

pharmacy:
  map:
    base:
      url: http://3.38.78.187/dir/
